#!/bin/sh

export LANG=C #w004
. /DISTRO_SPECS #v412 has DISTRO_VERSION, DISTRO_FILE_PREFIX

PATH="/bin:/sbin"
KERNELVER="`uname -r`"

if [ ! $1 ];then
 mount -t proc none /proc
 mount -t sysfs none /sys
 mount -t rootfs -o remount,rw rootfs /
 ln -s /proc/mounts /etc/mtab #resize2fs,e2fsck need this.
fi

RDSH=""
if [ "$pfix" ];then
 for ONEFIX in `echo -n "$pfix" | tr ',' ' '`
 do
  case $ONEFIX in
   ram)     PRAMONLY="yes";;      #run in ram only (do not load ${DISTRO_FILE_PREFIX}save).
   rdsh)    RDSH="yes";;          #exit to shell in initial ramdisk.
   rdsh0)   RDSH="0";;            #drop out early, before loading drivers.
   rdsh6)   RDSH="6";;            #w091027 drop out just before mount layerfs.
   nox)     PNOX="yes";;          #do not start X.
   clean)   PCLEAN="yes";;        #force version upgrade and cleanup.
   purge)   PPURGE="yes";;        #radical cleanup for broken system.
   copy)    PCOPY="yes";;         #copy .sfs files into ram.
   nocopy)  PNOCOPY="yes";;        #do not copy .sfs files into ram (default is copy if enough ram).
   fsck)    PFSCK="yes";;         #do a fsck of ${DISTRO_FILE_PREFIX}save file.
   [0-9]*)  PIGNORELAST=$ONEFIX;; #blacklist last $ONEFIX folders (multisession).
  esac
 done
fi

clear

echo "Meghajtók vizsgálása" > /dev/console
probepart_init > /tmp/devices
echo "" > /tmp/mount_dev
if [ "$pmedia" = "cd" ];then
 CDDEV=$(cat /tmp/devices | grep -E '^sr|^iso9660')
 echo "$CDDEV" >> /tmp/mount_dev
elif [ "$pmedia" = "usbflash" -o "$pmedia" = "flash" ];then
 for usb in $(cat /tmp/devices | grep sd )
 do
  ONEPART=$(echo "$usb" | cut -f1 -d'|' | cut -f3 -d'/' | sed s'/.$//')
  [ ! -z $(readlink $ONEPART | grep usb) ]&& echo "$usb" >> /tmp/mount_dev
 done
elif [ "$pdev1" ];then
 cat /tmp/devices | grep $pdev1 >> /tmp/mount_dev
else
 cp /tmp/devices /tmp/mount_dev
fi
if [ -z $(cat /tmp/mount_dev) ];then
 echo "Nem találtam csatolható meghajtót." > /dev/console
else
 echo "Elérhető meghajtók:" > /dev/console
 cat /tmp/mount_dev > /dev/console
fi

if [ $pupsfs ];then #ex: sda3:/subdir/puppy.sfs
 echo $(echo "$pupsfs" | cut -f1 -d':') > /tmp/mount_dev
 if [ -z $(echo '$pupsfs' | cut -f2 -d':' | cut -f2 -d'/' | grep '.sfs$') ]
  PSUBDIR=$(echo '$pupsfs' | cut -f2 -d':' | cut -f2 -d'/' | cut -f1 -d'/' )
  PUPSFS2=$(echo '$pupsfs' | cut -f2 -d':' | cut -f2 -d'/' | cut -f2 -d'/' )
  [ "$PUPSFS2" != "DISTRO_PUPPYSFS"]&& echo -e "A  $PUPSFS2 fájl neve nem egyezik az initrdben megadottal,\nmelynek neve : $DISTRO_PUPPYSFS " > /dev/console
 fi
fi
exec /bin/sh >/dev/console 2>&1
